name: Dakota Wisdom Lorance
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-cayman
paginate: 5
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
