author: Dakota Wisdom Lorance
name: Dakota Wisdom Lorance
email: admin@slyb--ts.com
brand: dwl
title: DWL Blog
description: A container for all of my projects!
url: https://slyboots.github.io
github: [metadata]
url: https://dakotalorance.com
enforce_ssl: dakotalorance.com
paginate: 5
paginate_path: "/blog/page:num/"
permalink: /blog/:year/:month/:day/:title
verbose: true
excerpt_separator: "<!--more-->"

# Build settings
markdown: kramdown
tsc: /home/dwl/.nvm/versions/node/v8.2.1/bin/tsc
js_dest: js/
incremental: false

exclude:
  - package.json
  - package-lock.json
  - node_modules
  - .vscode/
  - webpack.main.js
  - .jekyll-metadata
  - manage
sass:
  sass_dir: _sass
  style: compact

plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-sitemap

kramdown:
  auto_ids:       false
  input:          kramdown
  entity_output:  symbolic
