author: Dakota Wisdom Lorance
name: Dakota Wisdom Lorance
email: admin@slyb--ts.com
brand: dwl
title: DWL Blog
description: The official blog of Dakota!
url: https://slyboots.github.io
github: [metadata]

markdown: kramdown

paginate: 5
paginate_path: "/blog/page:num/"
permalink: /blog/:year/:month/:day/:title

sass:
  sass_dir: _sass
  style: compact

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - package-lock.json
  - node_modules
  - .vscode/

verbose: true